project:
  type: website

website: 
  title: "MCR"
  navbar: 
    tools:
      - icon: github
        href: https://github.com/mine-cetinkaya-rundel/quarto-pydata-website-completed
    left:
      - href: index.qmd
      - href: blog.qmd
      - href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto